# Generated by configure script - do not edit

PREFIX = /mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp
BUILD_TYPE = Release
ENABLE_TESTS = 1
ENABLE_DOCS = 1

# Compiler flags
ifeq ($(BUILD_TYPE),Debug)
    CXXFLAGS += -g -O0 -DDEBUG
else
    CXXFLAGS += -O2 -DNDEBUG
endif

# Installation paths
bindir = $(PREFIX)/bin
libdir = $(PREFIX)/lib
includedir = $(PREFIX)/include
docdir = $(PREFIX)/share/doc/chunker

# Dependencies
HAVE_GTEST = 1
HAVE_DOXYGEN = 1

# Additional include paths
ifeq (,Windows_NT)
    EXTRA_INCLUDES = -I/installed/x64-windows/include
else
    EXTRA_INCLUDES = -I/usr/include/gtest -I/usr/local/include/gtest
endif

CXXFLAGS += 
