# Generated by configure script - do not edit

PREFIX = /usr/local
BUILD_TYPE = Release
ENABLE_TESTS = 0
ENABLE_DOCS = 1

# Compiler flags
ifeq ($(BUILD_TYPE),Debug)
    CXXFLAGS += -g -O0 -DDEBUG
else
    CXXFLAGS += -O2 -DNDEBUG
endif

# Installation paths
bindir = $(PREFIX)/bin
libdir = $(PREFIX)/lib
includedir = $(PREFIX)/include
docdir = $(PREFIX)/share/doc/chunker

# Dependencies
HAVE_GTEST = 0
HAVE_DOXYGEN = 1
