# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Include local make rules
-include Makefile.local

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp/CMakeFiles" "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chunk_processor

# Build rule for target.
chunk_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunk_processor
.PHONY : chunk_processor

# fast build rule for target.
chunk_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/build
.PHONY : chunk_processor/fast

#=============================================================================
# Target rules for targets named chunk_processor_exe

# Build rule for target.
chunk_processor_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunk_processor_exe
.PHONY : chunk_processor_exe

# fast build rule for target.
chunk_processor_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/build
.PHONY : chunk_processor_exe/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/advanced_structures_test.o: tests/advanced_structures_test.cpp.o
.PHONY : tests/advanced_structures_test.o

# target to build an object file
tests/advanced_structures_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_structures_test.cpp.o
.PHONY : tests/advanced_structures_test.cpp.o

tests/advanced_structures_test.i: tests/advanced_structures_test.cpp.i
.PHONY : tests/advanced_structures_test.i

# target to preprocess a source file
tests/advanced_structures_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_structures_test.cpp.i
.PHONY : tests/advanced_structures_test.cpp.i

tests/advanced_structures_test.s: tests/advanced_structures_test.cpp.s
.PHONY : tests/advanced_structures_test.s

# target to generate assembly for a file
tests/advanced_structures_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_structures_test.cpp.s
.PHONY : tests/advanced_structures_test.cpp.s

tests/chunk_compression_test.o: tests/chunk_compression_test.cpp.o
.PHONY : tests/chunk_compression_test.o

# target to build an object file
tests/chunk_compression_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_compression_test.cpp.o
.PHONY : tests/chunk_compression_test.cpp.o

tests/chunk_compression_test.i: tests/chunk_compression_test.cpp.i
.PHONY : tests/chunk_compression_test.i

# target to preprocess a source file
tests/chunk_compression_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_compression_test.cpp.i
.PHONY : tests/chunk_compression_test.cpp.i

tests/chunk_compression_test.s: tests/chunk_compression_test.cpp.s
.PHONY : tests/chunk_compression_test.s

# target to generate assembly for a file
tests/chunk_compression_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_compression_test.cpp.s
.PHONY : tests/chunk_compression_test.cpp.s

tests/chunk_strategies_test.o: tests/chunk_strategies_test.cpp.o
.PHONY : tests/chunk_strategies_test.o

# target to build an object file
tests/chunk_strategies_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_strategies_test.cpp.o
.PHONY : tests/chunk_strategies_test.cpp.o

tests/chunk_strategies_test.i: tests/chunk_strategies_test.cpp.i
.PHONY : tests/chunk_strategies_test.i

# target to preprocess a source file
tests/chunk_strategies_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_strategies_test.cpp.i
.PHONY : tests/chunk_strategies_test.cpp.i

tests/chunk_strategies_test.s: tests/chunk_strategies_test.cpp.s
.PHONY : tests/chunk_strategies_test.s

# target to generate assembly for a file
tests/chunk_strategies_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_strategies_test.cpp.s
.PHONY : tests/chunk_strategies_test.cpp.s

tests/chunk_test.o: tests/chunk_test.cpp.o
.PHONY : tests/chunk_test.o

# target to build an object file
tests/chunk_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_test.cpp.o
.PHONY : tests/chunk_test.cpp.o

tests/chunk_test.i: tests/chunk_test.cpp.i
.PHONY : tests/chunk_test.i

# target to preprocess a source file
tests/chunk_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_test.cpp.i
.PHONY : tests/chunk_test.cpp.i

tests/chunk_test.s: tests/chunk_test.cpp.s
.PHONY : tests/chunk_test.s

# target to generate assembly for a file
tests/chunk_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_test.cpp.s
.PHONY : tests/chunk_test.cpp.s

tests/parallel_chunk_test.o: tests/parallel_chunk_test.cpp.o
.PHONY : tests/parallel_chunk_test.o

# target to build an object file
tests/parallel_chunk_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/parallel_chunk_test.cpp.o
.PHONY : tests/parallel_chunk_test.cpp.o

tests/parallel_chunk_test.i: tests/parallel_chunk_test.cpp.i
.PHONY : tests/parallel_chunk_test.i

# target to preprocess a source file
tests/parallel_chunk_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/parallel_chunk_test.cpp.i
.PHONY : tests/parallel_chunk_test.cpp.i

tests/parallel_chunk_test.s: tests/parallel_chunk_test.cpp.s
.PHONY : tests/parallel_chunk_test.s

# target to generate assembly for a file
tests/parallel_chunk_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/parallel_chunk_test.cpp.s
.PHONY : tests/parallel_chunk_test.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... chunk_processor"
	@echo "... chunk_processor_exe"
	@echo "... run_tests"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/advanced_structures_test.o"
	@echo "... tests/advanced_structures_test.i"
	@echo "... tests/advanced_structures_test.s"
	@echo "... tests/chunk_compression_test.o"
	@echo "... tests/chunk_compression_test.i"
	@echo "... tests/chunk_compression_test.s"
	@echo "... tests/chunk_strategies_test.o"
	@echo "... tests/chunk_strategies_test.i"
	@echo "... tests/chunk_strategies_test.s"
	@echo "... tests/chunk_test.o"
	@echo "... tests/chunk_test.i"
	@echo "... tests/chunk_test.s"
	@echo "... tests/parallel_chunk_test.o"
	@echo "... tests/parallel_chunk_test.i"
	@echo "... tests/parallel_chunk_test.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

