# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp/CMakeFiles" "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/jonat/OneDrive/Documents/Python Scripts/chunking_cpp/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chunk_processor

# Build rule for target.
chunk_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunk_processor
.PHONY : chunk_processor

# fast build rule for target.
chunk_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/build
.PHONY : chunk_processor/fast

#=============================================================================
# Target rules for targets named chunk_processor_exe

# Build rule for target.
chunk_processor_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunk_processor_exe
.PHONY : chunk_processor_exe

# fast build rule for target.
chunk_processor_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/build
.PHONY : chunk_processor_exe/fast

#=============================================================================
# Target rules for targets named benchmark_exe

# Build rule for target.
benchmark_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_exe
.PHONY : benchmark_exe

# fast build rule for target.
benchmark_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_exe.dir/build.make CMakeFiles/benchmark_exe.dir/build
.PHONY : benchmark_exe/fast

#=============================================================================
# Target rules for targets named neural_chunking_demo

# Build rule for target.
neural_chunking_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neural_chunking_demo
.PHONY : neural_chunking_demo

# fast build rule for target.
neural_chunking_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking_demo.dir/build.make CMakeFiles/neural_chunking_demo.dir/build
.PHONY : neural_chunking_demo/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named sophisticated_chunking

# Build rule for target.
sophisticated_chunking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sophisticated_chunking
.PHONY : sophisticated_chunking

# fast build rule for target.
sophisticated_chunking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sophisticated_chunking.dir/build.make CMakeFiles/sophisticated_chunking.dir/build
.PHONY : sophisticated_chunking/fast

#=============================================================================
# Target rules for targets named neural_chunking

# Build rule for target.
neural_chunking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neural_chunking
.PHONY : neural_chunking

# fast build rule for target.
neural_chunking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking.dir/build.make CMakeFiles/neural_chunking.dir/build
.PHONY : neural_chunking/fast

#=============================================================================
# Target rules for targets named chunk_benchmark

# Build rule for target.
chunk_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunk_benchmark
.PHONY : chunk_benchmark

# fast build rule for target.
chunk_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_benchmark.dir/build.make CMakeFiles/chunk_benchmark.dir/build
.PHONY : chunk_benchmark/fast

#=============================================================================
# Target rules for targets named chunking_methods_sophisticated_test

# Build rule for target.
chunking_methods_sophisticated_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunking_methods_sophisticated_test
.PHONY : chunking_methods_sophisticated_test

# fast build rule for target.
chunking_methods_sophisticated_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_methods_sophisticated_test.dir/build.make CMakeFiles/chunking_methods_sophisticated_test.dir/build
.PHONY : chunking_methods_sophisticated_test/fast

#=============================================================================
# Target rules for targets named neural_network_test

# Build rule for target.
neural_network_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neural_network_test
.PHONY : neural_network_test

# fast build rule for target.
neural_network_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/build
.PHONY : neural_network_test/fast

#=============================================================================
# Target rules for targets named chunking_cpp

# Build rule for target.
chunking_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunking_cpp
.PHONY : chunking_cpp

# fast build rule for target.
chunking_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_cpp.dir/build.make CMakeFiles/chunking_cpp.dir/build
.PHONY : chunking_cpp/fast

bindings/python/chunk_bindings.o: bindings/python/chunk_bindings.cpp.o
.PHONY : bindings/python/chunk_bindings.o

# target to build an object file
bindings/python/chunk_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_cpp.dir/build.make CMakeFiles/chunking_cpp.dir/bindings/python/chunk_bindings.cpp.o
.PHONY : bindings/python/chunk_bindings.cpp.o

bindings/python/chunk_bindings.i: bindings/python/chunk_bindings.cpp.i
.PHONY : bindings/python/chunk_bindings.i

# target to preprocess a source file
bindings/python/chunk_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_cpp.dir/build.make CMakeFiles/chunking_cpp.dir/bindings/python/chunk_bindings.cpp.i
.PHONY : bindings/python/chunk_bindings.cpp.i

bindings/python/chunk_bindings.s: bindings/python/chunk_bindings.cpp.s
.PHONY : bindings/python/chunk_bindings.s

# target to generate assembly for a file
bindings/python/chunk_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_cpp.dir/build.make CMakeFiles/chunking_cpp.dir/bindings/python/chunk_bindings.cpp.s
.PHONY : bindings/python/chunk_bindings.cpp.s

src/benchmark.o: src/benchmark.cpp.o
.PHONY : src/benchmark.o

# target to build an object file
src/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_exe.dir/build.make CMakeFiles/benchmark_exe.dir/src/benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_benchmark.dir/build.make CMakeFiles/chunk_benchmark.dir/src/benchmark.cpp.o
.PHONY : src/benchmark.cpp.o

src/benchmark.i: src/benchmark.cpp.i
.PHONY : src/benchmark.i

# target to preprocess a source file
src/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_exe.dir/build.make CMakeFiles/benchmark_exe.dir/src/benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_benchmark.dir/build.make CMakeFiles/chunk_benchmark.dir/src/benchmark.cpp.i
.PHONY : src/benchmark.cpp.i

src/benchmark.s: src/benchmark.cpp.s
.PHONY : src/benchmark.s

# target to generate assembly for a file
src/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_exe.dir/build.make CMakeFiles/benchmark_exe.dir/src/benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_benchmark.dir/build.make CMakeFiles/chunk_benchmark.dir/src/benchmark.cpp.s
.PHONY : src/benchmark.cpp.s

src/demo_neural_chunking.o: src/demo_neural_chunking.cpp.o
.PHONY : src/demo_neural_chunking.o

# target to build an object file
src/demo_neural_chunking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/demo_neural_chunking.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking_demo.dir/build.make CMakeFiles/neural_chunking_demo.dir/src/demo_neural_chunking.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking.dir/build.make CMakeFiles/neural_chunking.dir/src/demo_neural_chunking.cpp.o
.PHONY : src/demo_neural_chunking.cpp.o

src/demo_neural_chunking.i: src/demo_neural_chunking.cpp.i
.PHONY : src/demo_neural_chunking.i

# target to preprocess a source file
src/demo_neural_chunking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/demo_neural_chunking.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking_demo.dir/build.make CMakeFiles/neural_chunking_demo.dir/src/demo_neural_chunking.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking.dir/build.make CMakeFiles/neural_chunking.dir/src/demo_neural_chunking.cpp.i
.PHONY : src/demo_neural_chunking.cpp.i

src/demo_neural_chunking.s: src/demo_neural_chunking.cpp.s
.PHONY : src/demo_neural_chunking.s

# target to generate assembly for a file
src/demo_neural_chunking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/demo_neural_chunking.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking_demo.dir/build.make CMakeFiles/neural_chunking_demo.dir/src/demo_neural_chunking.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_chunking.dir/build.make CMakeFiles/neural_chunking.dir/src/demo_neural_chunking.cpp.s
.PHONY : src/demo_neural_chunking.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor_exe.dir/build.make CMakeFiles/chunk_processor_exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sophisticated_chunking_demo.o: src/sophisticated_chunking_demo.cpp.o
.PHONY : src/sophisticated_chunking_demo.o

# target to build an object file
src/sophisticated_chunking_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/sophisticated_chunking_demo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sophisticated_chunking.dir/build.make CMakeFiles/sophisticated_chunking.dir/src/sophisticated_chunking_demo.cpp.o
.PHONY : src/sophisticated_chunking_demo.cpp.o

src/sophisticated_chunking_demo.i: src/sophisticated_chunking_demo.cpp.i
.PHONY : src/sophisticated_chunking_demo.i

# target to preprocess a source file
src/sophisticated_chunking_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/sophisticated_chunking_demo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sophisticated_chunking.dir/build.make CMakeFiles/sophisticated_chunking.dir/src/sophisticated_chunking_demo.cpp.i
.PHONY : src/sophisticated_chunking_demo.cpp.i

src/sophisticated_chunking_demo.s: src/sophisticated_chunking_demo.cpp.s
.PHONY : src/sophisticated_chunking_demo.s

# target to generate assembly for a file
src/sophisticated_chunking_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunk_processor.dir/build.make CMakeFiles/chunk_processor.dir/src/sophisticated_chunking_demo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sophisticated_chunking.dir/build.make CMakeFiles/sophisticated_chunking.dir/src/sophisticated_chunking_demo.cpp.s
.PHONY : src/sophisticated_chunking_demo.cpp.s

tests/advanced_chunk_strategies_test.o: tests/advanced_chunk_strategies_test.cpp.o
.PHONY : tests/advanced_chunk_strategies_test.o

# target to build an object file
tests/advanced_chunk_strategies_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_chunk_strategies_test.cpp.o
.PHONY : tests/advanced_chunk_strategies_test.cpp.o

tests/advanced_chunk_strategies_test.i: tests/advanced_chunk_strategies_test.cpp.i
.PHONY : tests/advanced_chunk_strategies_test.i

# target to preprocess a source file
tests/advanced_chunk_strategies_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_chunk_strategies_test.cpp.i
.PHONY : tests/advanced_chunk_strategies_test.cpp.i

tests/advanced_chunk_strategies_test.s: tests/advanced_chunk_strategies_test.cpp.s
.PHONY : tests/advanced_chunk_strategies_test.s

# target to generate assembly for a file
tests/advanced_chunk_strategies_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_chunk_strategies_test.cpp.s
.PHONY : tests/advanced_chunk_strategies_test.cpp.s

tests/advanced_structures_test.o: tests/advanced_structures_test.cpp.o
.PHONY : tests/advanced_structures_test.o

# target to build an object file
tests/advanced_structures_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_structures_test.cpp.o
.PHONY : tests/advanced_structures_test.cpp.o

tests/advanced_structures_test.i: tests/advanced_structures_test.cpp.i
.PHONY : tests/advanced_structures_test.i

# target to preprocess a source file
tests/advanced_structures_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_structures_test.cpp.i
.PHONY : tests/advanced_structures_test.cpp.i

tests/advanced_structures_test.s: tests/advanced_structures_test.cpp.s
.PHONY : tests/advanced_structures_test.s

# target to generate assembly for a file
tests/advanced_structures_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/advanced_structures_test.cpp.s
.PHONY : tests/advanced_structures_test.cpp.s

tests/chunk_compression_test.o: tests/chunk_compression_test.cpp.o
.PHONY : tests/chunk_compression_test.o

# target to build an object file
tests/chunk_compression_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_compression_test.cpp.o
.PHONY : tests/chunk_compression_test.cpp.o

tests/chunk_compression_test.i: tests/chunk_compression_test.cpp.i
.PHONY : tests/chunk_compression_test.i

# target to preprocess a source file
tests/chunk_compression_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_compression_test.cpp.i
.PHONY : tests/chunk_compression_test.cpp.i

tests/chunk_compression_test.s: tests/chunk_compression_test.cpp.s
.PHONY : tests/chunk_compression_test.s

# target to generate assembly for a file
tests/chunk_compression_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_compression_test.cpp.s
.PHONY : tests/chunk_compression_test.cpp.s

tests/chunk_strategies_test.o: tests/chunk_strategies_test.cpp.o
.PHONY : tests/chunk_strategies_test.o

# target to build an object file
tests/chunk_strategies_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_strategies_test.cpp.o
.PHONY : tests/chunk_strategies_test.cpp.o

tests/chunk_strategies_test.i: tests/chunk_strategies_test.cpp.i
.PHONY : tests/chunk_strategies_test.i

# target to preprocess a source file
tests/chunk_strategies_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_strategies_test.cpp.i
.PHONY : tests/chunk_strategies_test.cpp.i

tests/chunk_strategies_test.s: tests/chunk_strategies_test.cpp.s
.PHONY : tests/chunk_strategies_test.s

# target to generate assembly for a file
tests/chunk_strategies_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_strategies_test.cpp.s
.PHONY : tests/chunk_strategies_test.cpp.s

tests/chunk_test.o: tests/chunk_test.cpp.o
.PHONY : tests/chunk_test.o

# target to build an object file
tests/chunk_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_test.cpp.o
.PHONY : tests/chunk_test.cpp.o

tests/chunk_test.i: tests/chunk_test.cpp.i
.PHONY : tests/chunk_test.i

# target to preprocess a source file
tests/chunk_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_test.cpp.i
.PHONY : tests/chunk_test.cpp.i

tests/chunk_test.s: tests/chunk_test.cpp.s
.PHONY : tests/chunk_test.s

# target to generate assembly for a file
tests/chunk_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunk_test.cpp.s
.PHONY : tests/chunk_test.cpp.s

tests/chunking_methods_sophisticated_test.o: tests/chunking_methods_sophisticated_test.cpp.o
.PHONY : tests/chunking_methods_sophisticated_test.o

# target to build an object file
tests/chunking_methods_sophisticated_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunking_methods_sophisticated_test.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_methods_sophisticated_test.dir/build.make CMakeFiles/chunking_methods_sophisticated_test.dir/tests/chunking_methods_sophisticated_test.cpp.o
.PHONY : tests/chunking_methods_sophisticated_test.cpp.o

tests/chunking_methods_sophisticated_test.i: tests/chunking_methods_sophisticated_test.cpp.i
.PHONY : tests/chunking_methods_sophisticated_test.i

# target to preprocess a source file
tests/chunking_methods_sophisticated_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunking_methods_sophisticated_test.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_methods_sophisticated_test.dir/build.make CMakeFiles/chunking_methods_sophisticated_test.dir/tests/chunking_methods_sophisticated_test.cpp.i
.PHONY : tests/chunking_methods_sophisticated_test.cpp.i

tests/chunking_methods_sophisticated_test.s: tests/chunking_methods_sophisticated_test.cpp.s
.PHONY : tests/chunking_methods_sophisticated_test.s

# target to generate assembly for a file
tests/chunking_methods_sophisticated_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/chunking_methods_sophisticated_test.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chunking_methods_sophisticated_test.dir/build.make CMakeFiles/chunking_methods_sophisticated_test.dir/tests/chunking_methods_sophisticated_test.cpp.s
.PHONY : tests/chunking_methods_sophisticated_test.cpp.s

tests/parallel_chunk_test.o: tests/parallel_chunk_test.cpp.o
.PHONY : tests/parallel_chunk_test.o

# target to build an object file
tests/parallel_chunk_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/parallel_chunk_test.cpp.o
.PHONY : tests/parallel_chunk_test.cpp.o

tests/parallel_chunk_test.i: tests/parallel_chunk_test.cpp.i
.PHONY : tests/parallel_chunk_test.i

# target to preprocess a source file
tests/parallel_chunk_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/parallel_chunk_test.cpp.i
.PHONY : tests/parallel_chunk_test.cpp.i

tests/parallel_chunk_test.s: tests/parallel_chunk_test.cpp.s
.PHONY : tests/parallel_chunk_test.s

# target to generate assembly for a file
tests/parallel_chunk_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/parallel_chunk_test.cpp.s
.PHONY : tests/parallel_chunk_test.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

tests/test_neuralnetwork.o: tests/test_neuralnetwork.cpp.o
.PHONY : tests/test_neuralnetwork.o

# target to build an object file
tests/test_neuralnetwork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_neuralnetwork.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/tests/test_neuralnetwork.cpp.o
.PHONY : tests/test_neuralnetwork.cpp.o

tests/test_neuralnetwork.i: tests/test_neuralnetwork.cpp.i
.PHONY : tests/test_neuralnetwork.i

# target to preprocess a source file
tests/test_neuralnetwork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_neuralnetwork.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/tests/test_neuralnetwork.cpp.i
.PHONY : tests/test_neuralnetwork.cpp.i

tests/test_neuralnetwork.s: tests/test_neuralnetwork.cpp.s
.PHONY : tests/test_neuralnetwork.s

# target to generate assembly for a file
tests/test_neuralnetwork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_neuralnetwork.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/tests/test_neuralnetwork.cpp.s
.PHONY : tests/test_neuralnetwork.cpp.s

tests/utils_test.o: tests/utils_test.cpp.o
.PHONY : tests/utils_test.o

# target to build an object file
tests/utils_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/utils_test.cpp.o
.PHONY : tests/utils_test.cpp.o

tests/utils_test.i: tests/utils_test.cpp.i
.PHONY : tests/utils_test.i

# target to preprocess a source file
tests/utils_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/utils_test.cpp.i
.PHONY : tests/utils_test.cpp.i

tests/utils_test.s: tests/utils_test.cpp.s
.PHONY : tests/utils_test.s

# target to generate assembly for a file
tests/utils_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/utils_test.cpp.s
.PHONY : tests/utils_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... coverage"
	@echo "... benchmark_exe"
	@echo "... chunk_benchmark"
	@echo "... chunk_processor"
	@echo "... chunk_processor_exe"
	@echo "... chunking_cpp"
	@echo "... chunking_methods_sophisticated_test"
	@echo "... neural_chunking"
	@echo "... neural_chunking_demo"
	@echo "... neural_network_test"
	@echo "... run_tests"
	@echo "... sophisticated_chunking"
	@echo "... bindings/python/chunk_bindings.o"
	@echo "... bindings/python/chunk_bindings.i"
	@echo "... bindings/python/chunk_bindings.s"
	@echo "... src/benchmark.o"
	@echo "... src/benchmark.i"
	@echo "... src/benchmark.s"
	@echo "... src/demo_neural_chunking.o"
	@echo "... src/demo_neural_chunking.i"
	@echo "... src/demo_neural_chunking.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sophisticated_chunking_demo.o"
	@echo "... src/sophisticated_chunking_demo.i"
	@echo "... src/sophisticated_chunking_demo.s"
	@echo "... tests/advanced_chunk_strategies_test.o"
	@echo "... tests/advanced_chunk_strategies_test.i"
	@echo "... tests/advanced_chunk_strategies_test.s"
	@echo "... tests/advanced_structures_test.o"
	@echo "... tests/advanced_structures_test.i"
	@echo "... tests/advanced_structures_test.s"
	@echo "... tests/chunk_compression_test.o"
	@echo "... tests/chunk_compression_test.i"
	@echo "... tests/chunk_compression_test.s"
	@echo "... tests/chunk_strategies_test.o"
	@echo "... tests/chunk_strategies_test.i"
	@echo "... tests/chunk_strategies_test.s"
	@echo "... tests/chunk_test.o"
	@echo "... tests/chunk_test.i"
	@echo "... tests/chunk_test.s"
	@echo "... tests/chunking_methods_sophisticated_test.o"
	@echo "... tests/chunking_methods_sophisticated_test.i"
	@echo "... tests/chunking_methods_sophisticated_test.s"
	@echo "... tests/parallel_chunk_test.o"
	@echo "... tests/parallel_chunk_test.i"
	@echo "... tests/parallel_chunk_test.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
	@echo "... tests/test_neuralnetwork.o"
	@echo "... tests/test_neuralnetwork.i"
	@echo "... tests/test_neuralnetwork.s"
	@echo "... tests/utils_test.o"
	@echo "... tests/utils_test.i"
	@echo "... tests/utils_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

