chunk_utils::ChunkManipulator< T > Class Template Reference
#include <utils.hpp>
Static Public Member Functions
static std::vector< std::vector< T > > filter_chunks (const std::vector< std::vector< T > > &chunks, std::function< bool(const std::vector< T > &)> predicate)
static std::vector< std::vector< T > > merge_chunks (const std::vector< std::vector< T > > &chunks1, const std::vector< std::vector< T > > &chunks2)
static std::vector< std::vector< T > > transform_chunks (const std::vector< std::vector< T > > &chunks, std::function< std::vector< T >(const std::vector< T > &)> transformer)
Detailed Description
template<typename T>
class chunk_utils::ChunkManipulator< T >
Definition at line 52 of file utils.hpp.
Member Function Documentation
filter_chunks()
template<typename T >
static std::vector< std::vector< T > > chunk_utils::ChunkManipulator< T >::filter_chunks (const std::vector< std::vector< T > > & chunks, std::function< bool(const std::vector< T > &)> predicate) [inline], [static]
Definition at line 62 of file utils.hpp.
                                                                    {
        std::vector<std::vector<T>> result;
        std::copy_if(chunks.begin(), chunks.end(), std::back_inserter(result), predicate);
        return result;
    }
Referenced by TEST().
merge_chunks()
template<typename T >
static std::vector< std::vector< T > > chunk_utils::ChunkManipulator< T >::merge_chunks (const std::vector< std::vector< T > > & chunks1, const std::vector< std::vector< T > > & chunks2) [inline], [static]
Definition at line 54 of file utils.hpp.
                                                                                            {
        std::vector<std::vector<T>> result = chunks1;
        result.insert(result.end(), chunks2.begin(), chunks2.end());
        return result;
    }
Referenced by TEST().
transform_chunks()
template<typename T >
static std::vector< std::vector< T > > chunk_utils::ChunkManipulator< T >::transform_chunks (const std::vector< std::vector< T > > & chunks, std::function< std::vector< T >(const std::vector< T > &)> transformer) [inline], [static]
Definition at line 70 of file utils.hpp.
                                                                                 {
        std::vector<std::vector<T>> result;
        std::transform(chunks.begin(), chunks.end(), std::back_inserter(result), transformer);
        return result;
    }
Referenced by TEST().
The documentation for this class was generated from the following file:
utils.hpp