chunk_strategies::EntropyStrategy< T > Class Template Reference
Strategy for chunking based on entropy thresholds.
#include <chunk_strategies.hpp>
Public Member Functions
EntropyStrategy (double threshold)
std::vector< std::vector< T > > apply (const std::vector< T > &data) const override
Applies the chunking strategy to the data.
Private Member Functions
double calculate_entropy (const std::vector< T > &chunk) const
Private Attributes
double threshold_
Detailed Description
template<typename T>
class chunk_strategies::EntropyStrategy< T >
Strategy for chunking based on entropy thresholds.
Definition at line 131 of file chunk_strategies.hpp.
Constructor & Destructor Documentation
EntropyStrategy()
template<typename T >
chunk_strategies::EntropyStrategy< T >::EntropyStrategy (double threshold) [inline], [explicit]
Definition at line 153 of file chunk_strategies.hpp.
: threshold_(threshold) {}
Member Function Documentation
apply()
template<typename T >
std::vector< std::vector< T > > chunk_strategies::EntropyStrategy< T >::apply (const std::vector< T > & data) const [inline], [override], [virtual]
Applies the chunking strategy to the data.
Parameters
data The data to chunk
Returns
A vector of chunks
Implements chunk_strategies::ChunkStrategy< T >.
Definition at line 155 of file chunk_strategies.hpp.
                                                                           {
        std::vector<std::vector<T>> chunks;
        std::vector<T> current_chunk;
        for (const auto& value : data) {
            current_chunk.push_back(value);
            if (calculate_entropy(current_chunk) > threshold_) {
                if (current_chunk.size() > 1) {
                    current_chunk.pop_back();
                    chunks.push_back(current_chunk);
                    current_chunk = {value};
                }
            }
        }
        if (!current_chunk.empty()) {
            chunks.push_back(current_chunk);
        }
        return chunks;
    }
References chunk_strategies::EntropyStrategy< T >::calculate_entropy(), and chunk_strategies::EntropyStrategy< T >::threshold_.
calculate_entropy()
template<typename T >
double chunk_strategies::EntropyStrategy< T >::calculate_entropy (const std::vector< T > & chunk) const [inline], [private]
Definition at line 134 of file chunk_strategies.hpp.
                                                              {
        if (chunk.empty())
            return 0.0;
        std::map<T, int> freq;
        for (const auto& val : chunk) {
            freq[val]++;
        }
        double entropy = 0.0;
        for (const auto& [_, count] : freq) {
            double p = static_cast<double>(count) / chunk.size();
            entropy -= p * std::log2(p);
        }
        return entropy;
    }
Referenced by chunk_strategies::EntropyStrategy< std::string >::apply(), and chunk_strategies::EntropyStrategy< T >::apply().
Member Data Documentation
threshold_
template<typename T >
double chunk_strategies::EntropyStrategy< T >::threshold_ [private]
Definition at line 132 of file chunk_strategies.hpp.
Referenced by chunk_strategies::EntropyStrategy< std::string >::apply(), and chunk_strategies::EntropyStrategy< T >::apply().
The documentation for this class was generated from the following file:
chunk_strategies.hpp