advanced_structures::FractalPatternsChunk< T > Class Template Reference
Fractal pattern-based chunking implementation.
#include <advanced_structures.hpp>
Public Member Functions
FractalPatternsChunk (size_t size=3, double threshold=0.8)
std::vector< std::vector< T > > chunk (const std::vector< T > &data)
Protected Member Functions
virtual bool hasPattern (const std::vector< T > &chunk)
Private Attributes
size_t pattern_size
double similarity_threshold
Detailed Description
template<typename T>
class advanced_structures::FractalPatternsChunk< T >
Fractal pattern-based chunking implementation.
Template Parameters
T The type of elements to be chunked
Definition at line 544 of file advanced_structures.hpp.
Constructor & Destructor Documentation
FractalPatternsChunk()
template<typename T >
advanced_structures::FractalPatternsChunk< T >::FractalPatternsChunk (size_t size = 3, double threshold = 0.8) [inline]
Definition at line 550 of file advanced_structures.hpp.
        : pattern_size(size), similarity_threshold(threshold) {}
Member Function Documentation
chunk()
template<typename T >
std::vector< std::vector< T > > advanced_structures::FractalPatternsChunk< T >::chunk (const std::vector< T > & data) [inline]
Definition at line 553 of file advanced_structures.hpp.
                                                            {
        std::vector<std::vector<T>> result;
        if (data.empty())
            return result;
        std::vector<T> current_chunk;
        for (const auto& item : data) {
            current_chunk.push_back(item);
            if (hasPattern(current_chunk)) {
                result.push_back(current_chunk);
                current_chunk.clear();
            }
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References advanced_structures::FractalPatternsChunk< T >::hasPattern().
Referenced by advanced_structures::FractalPatternsChunk< T >::hasPattern(), and TEST().
hasPattern()
template<typename T >
virtual bool advanced_structures::FractalPatternsChunk< T >::hasPattern (const std::vector< T > & chunk) [inline], [protected], [virtual]
Definition at line 575 of file advanced_structures.hpp.
                                                       {
        return chunk.size() >= pattern_size;
    }
References advanced_structures::FractalPatternsChunk< T >::chunk(), and advanced_structures::FractalPatternsChunk< T >::pattern_size.
Referenced by advanced_structures::FractalPatternsChunk< T >::chunk().
Member Data Documentation
pattern_size
template<typename T >
size_t advanced_structures::FractalPatternsChunk< T >::pattern_size [private]
Definition at line 546 of file advanced_structures.hpp.
Referenced by advanced_structures::FractalPatternsChunk< T >::hasPattern().
similarity_threshold
template<typename T >
double advanced_structures::FractalPatternsChunk< T >::similarity_threshold [private]
Definition at line 547 of file advanced_structures.hpp.
The documentation for this class was generated from the following file:
advanced_structures.hpp