chunk_strategies::PatternBasedStrategy< T > Class Template Reference
#include <chunk_strategies.hpp>
Public Member Functions
PatternBasedStrategy (size_t pattern_size)
PatternBasedStrategy (std::function< bool(T)> predicate)
std::vector< std::vector< T > > apply (const std::vector< T > &data) const override
Applies the chunking strategy to the data.
Private Member Functions
std::vector< std::vector< T > > chunk_by_predicate (const std::vector< T > &data) const
std::vector< std::vector< T > > chunk_by_size (const std::vector< T > &data) const
template<typename U >
double compute_array_sum (const U &arr) const
size_t get_pattern_size () const
const std::function< bool(T)> & get_predicate () const
void set_pattern_size (size_t size)
void set_predicate (std::function< bool(T)> pred)
Private Attributes
size_t pattern_size_
std::function< bool(T)> predicate_
Static Private Attributes
template<typename U >
static constexpr bool is_multidimensional_v = chunk_processing::is_multidimensional_v<U>
Detailed Description
template<typename T>
class chunk_strategies::PatternBasedStrategy< T >
Definition at line 196 of file chunk_strategies.hpp.
Constructor & Destructor Documentation
PatternBasedStrategy() [1/2]
template<typename T >
chunk_strategies::PatternBasedStrategy< T >::PatternBasedStrategy (size_t pattern_size) [inline], [explicit]
Definition at line 224 of file chunk_strategies.hpp.
        : pattern_size_(pattern_size), predicate_(nullptr) {}
PatternBasedStrategy() [2/2]
template<typename T >
chunk_strategies::PatternBasedStrategy< T >::PatternBasedStrategy (std::function< bool(T)> predicate) [inline], [explicit]
Definition at line 228 of file chunk_strategies.hpp.
        : pattern_size_(0), predicate_(predicate) {}
Member Function Documentation
apply()
template<typename T >
std::vector< std::vector< T > > chunk_strategies::PatternBasedStrategy< T >::apply (const std::vector< T > & data) const [inline], [override], [virtual]
Applies the chunking strategy to the data.
Parameters
data The data to chunk
Returns
A vector of chunks
Implements chunk_strategies::ChunkStrategy< T >.
Definition at line 231 of file chunk_strategies.hpp.
                                                                           {
        if (data.empty()) {
            return {};
        }
        if constexpr (is_multidimensional_v<T>) {
            // Handle multi-dimensional arrays
            if (predicate_) {
                return chunk_by_predicate(data);
            } else {
                return chunk_by_size(data);
            }
        } else {
            // Existing single-dimension logic
            // ...
        }
    }
References chunk_strategies::PatternBasedStrategy< T >::chunk_by_predicate(), chunk_strategies::PatternBasedStrategy< T >::chunk_by_size(), and chunk_strategies::PatternBasedStrategy< T >::predicate_.
chunk_by_predicate()
template<typename T >
std::vector< std::vector< T > > chunk_strategies::PatternBasedStrategy< T >::chunk_by_predicate (const std::vector< T > & data) const [inline], [private]
Definition at line 250 of file chunk_strategies.hpp.
                                                                               {
        std::vector<std::vector<T>> result;
        std::vector<T> current_chunk;
        for (const auto& value : data) {
            if constexpr (is_multidimensional_v<T>) {
                if (predicate_(compute_array_sum(value))) {
                    if (!current_chunk.empty()) {
                        result.push_back(current_chunk);
                        current_chunk.clear();
                    }
                }
            } else {
                if (predicate_(value)) {
                    if (!current_chunk.empty()) {
                        result.push_back(current_chunk);
                        current_chunk.clear();
                    }
                }
            }
            current_chunk.push_back(value);
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References chunk_strategies::PatternBasedStrategy< T >::compute_array_sum(), and chunk_strategies::PatternBasedStrategy< T >::predicate_.
Referenced by chunk_strategies::PatternBasedStrategy< T >::apply().
chunk_by_size()
template<typename T >
std::vector< std::vector< T > > chunk_strategies::PatternBasedStrategy< T >::chunk_by_size (const std::vector< T > & data) const [inline], [private]
Definition at line 280 of file chunk_strategies.hpp.
                                                                          {
        if (pattern_size_ == 0) {
            return {data};
        }
        if (data.size() < pattern_size_) {
            return data.empty() ? std::vector<std::vector<T>>{} : std::vector<std::vector<T>>{data};
        }
        std::vector<std::vector<T>> result;
        for (size_t i = 0; i < data.size(); i += pattern_size_) {
            size_t end = std::min(i + pattern_size_, data.size());
            result.emplace_back(data.begin() + i, data.begin() + end);
        }
        return result;
    }
References chunk_strategies::PatternBasedStrategy< T >::pattern_size_.
Referenced by chunk_strategies::PatternBasedStrategy< T >::apply().
compute_array_sum()
template<typename T >
template<typename U >
double chunk_strategies::PatternBasedStrategy< T >::compute_array_sum (const U & arr) const [inline], [private]
Definition at line 202 of file chunk_strategies.hpp.
                                                 {
        if constexpr (chunk_processing::is_multidimensional_v<U>) {
            double sum = 0.0;
            size_t depth = 0;
            constexpr size_t MAX_DEPTH = 1000; // Prevent stack overflow
            
            for (const auto& inner : arr) {
                if (depth++ > MAX_DEPTH) {
                    throw std::runtime_error("Maximum recursion depth exceeded");
                }
                sum += compute_array_sum(inner);
            }
            return sum;
        } else if constexpr (chunk_processing::is_vector<U>::value) {
            return std::accumulate(arr.begin(), arr.end(), 0.0);
        } else {
            return static_cast<double>(arr);
        }
    }
References chunk_strategies::PatternBasedStrategy< T >::compute_array_sum().
Referenced by chunk_strategies::PatternBasedStrategy< T >::chunk_by_predicate(), and chunk_strategies::PatternBasedStrategy< T >::compute_array_sum().
get_pattern_size()
template<typename T >
size_t chunk_strategies::PatternBasedStrategy< T >::get_pattern_size () const [inline], [private]
Definition at line 298 of file chunk_strategies.hpp.
                                    {
        return pattern_size_;
    }
References chunk_strategies::PatternBasedStrategy< T >::pattern_size_.
get_predicate()
template<typename T >
const std::function< bool(T)> & chunk_strategies::PatternBasedStrategy< T >::get_predicate () const [inline], [private]
Definition at line 301 of file chunk_strategies.hpp.
                                                      {
        return predicate_;
    }
References chunk_strategies::PatternBasedStrategy< T >::predicate_.
set_pattern_size()
template<typename T >
void chunk_strategies::PatternBasedStrategy< T >::set_pattern_size (size_t size) [inline], [private]
Definition at line 306 of file chunk_strategies.hpp.
                                       {
        pattern_size_ = size;
    }
References chunk_strategies::PatternBasedStrategy< T >::pattern_size_.
set_predicate()
template<typename T >
void chunk_strategies::PatternBasedStrategy< T >::set_predicate (std::function< bool(T)> pred) [inline], [private]
Definition at line 309 of file chunk_strategies.hpp.
                                                  {
        predicate_ = std::move(pred);
    }
References chunk_strategies::PatternBasedStrategy< T >::predicate_.
Member Data Documentation
is_multidimensional_v
template<typename T >
template<typename U >
constexpr bool chunk_strategies::PatternBasedStrategy< T >::is_multidimensional_v = chunk_processing::is_multidimensional_v<U> [static], [constexpr], [private]
Definition at line 199 of file chunk_strategies.hpp.
pattern_size_
template<typename T >
size_t chunk_strategies::PatternBasedStrategy< T >::pattern_size_ [private]
Definition at line 314 of file chunk_strategies.hpp.
Referenced by chunk_strategies::PatternBasedStrategy< T >::chunk_by_size(), chunk_strategies::PatternBasedStrategy< T >::get_pattern_size(), and chunk_strategies::PatternBasedStrategy< T >::set_pattern_size().
predicate_
template<typename T >
std::function<bool(T)> chunk_strategies::PatternBasedStrategy< T >::predicate_ [private]
Definition at line 315 of file chunk_strategies.hpp.
Referenced by chunk_strategies::PatternBasedStrategy< T >::apply(), chunk_strategies::PatternBasedStrategy< T >::chunk_by_predicate(), chunk_strategies::PatternBasedStrategy< T >::get_predicate(), and chunk_strategies::PatternBasedStrategy< T >::set_predicate().
The documentation for this class was generated from the following file:
chunk_strategies.hpp