chunk_strategies::RecursiveSubChunkStrategy< T > Class Template Reference
Strategy for applying recursive sub-chunking.
#include <sub_chunk_strategies.hpp>
Public Member Functions
RecursiveSubChunkStrategy (std::shared_ptr< ChunkStrategy< T > > strategy, size_t max_depth=2, size_t min_chunk_size=1)
Construct a recursive sub-chunking strategy.
std::vector< std::vector< std::vector< T > > > apply (const std::vector< std::vector< T > > &chunks) override
Apply recursive sub-chunking to the input chunks.
Private Member Functions
std::vector< std::vector< std::vector< T > > > apply_recursive (const std::vector< std::vector< T > > &chunks, size_t current_depth)
Helper function for recursive chunking.
Private Attributes
size_t max_depth_
size_t min_chunk_size_
std::shared_ptr< ChunkStrategy< T > > strategy_
Detailed Description
template<typename T>
class chunk_strategies::RecursiveSubChunkStrategy< T >
Strategy for applying recursive sub-chunking.
Template Parameters
T The type of elements to process
Definition at line 52 of file sub_chunk_strategies.hpp.
Constructor & Destructor Documentation
RecursiveSubChunkStrategy()
template<typename T >
chunk_strategies::RecursiveSubChunkStrategy< T >::RecursiveSubChunkStrategy (std::shared_ptr< ChunkStrategy< T > > strategy, size_t max_depth = 2, size_t min_chunk_size = 1) [inline]
Construct a recursive sub-chunking strategy.
Parameters
strategy The base chunking strategy to apply recursively
max_depth Maximum recursion depth
min_chunk_size Minimum size for chunks to be processed
Definition at line 65 of file sub_chunk_strategies.hpp.
        : strategy_(strategy), max_depth_(max_depth), min_chunk_size_(min_chunk_size) {}
Member Function Documentation
apply()
template<typename T >
std::vector< std::vector< std::vector< T > > > chunk_strategies::RecursiveSubChunkStrategy< T >::apply (const std::vector< std::vector< T > > & chunks) [inline], [override], [virtual]
Apply recursive sub-chunking to the input chunks.
Parameters
chunks The input chunks to process
Returns
A vector of vectors of vectors containing the recursively sub-chunked data
Implements chunk_strategies::SubChunkStrategy< T >.
Definition at line 75 of file sub_chunk_strategies.hpp.
                                                          {
        return apply_recursive(chunks, 1);
    }
References chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive().
apply_recursive()
template<typename T >
std::vector< std::vector< std::vector< T > > > chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive (const std::vector< std::vector< T > > & chunks, size_t current_depth) [inline], [private]
Helper function for recursive chunking.
Parameters
chunks The chunks to process
current_depth Current recursion depth
Returns
Processed sub-chunks
This method recursively applies the chunking strategy:
Checks depth and size constraints
Applies base strategy to each chunk
Recursively processes sub-chunks if needed
Returns the hierarchical result
Definition at line 87 of file sub_chunk_strategies.hpp.
                                                                                 {
        /**
         * @details This method recursively applies the chunking strategy:
         * 1. Checks depth and size constraints
         * 2. Applies base strategy to each chunk
         * 3. Recursively processes sub-chunks if needed
         * 4. Returns the hierarchical result
         */
        std::vector<std::vector<std::vector<T>>> result;
        for (const auto& chunk : chunks) {
            if (current_depth >= max_depth_ || chunk.size() <= min_chunk_size_) {
                result.push_back({chunk});
                continue;
            }
            auto sub_chunks = strategy_->apply(chunk);
            if (current_depth < max_depth_) {
                auto recursive_result = apply_recursive(sub_chunks, current_depth + 1);
                result.insert(result.end(), recursive_result.begin(), recursive_result.end());
            } else {
                result.push_back(sub_chunks);
            }
        }
        return result;
    }
References chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive(), chunk_strategies::RecursiveSubChunkStrategy< T >::max_depth_, chunk_strategies::RecursiveSubChunkStrategy< T >::min_chunk_size_, and chunk_strategies::RecursiveSubChunkStrategy< T >::strategy_.
Referenced by chunk_strategies::RecursiveSubChunkStrategy< T >::apply(), and chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive().
Member Data Documentation
max_depth_
template<typename T >
size_t chunk_strategies::RecursiveSubChunkStrategy< T >::max_depth_ [private]
Definition at line 55 of file sub_chunk_strategies.hpp.
Referenced by chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive().
min_chunk_size_
template<typename T >
size_t chunk_strategies::RecursiveSubChunkStrategy< T >::min_chunk_size_ [private]
Definition at line 56 of file sub_chunk_strategies.hpp.
Referenced by chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive().
strategy_
template<typename T >
std::shared_ptr<ChunkStrategy<T> > chunk_strategies::RecursiveSubChunkStrategy< T >::strategy_ [private]
Definition at line 54 of file sub_chunk_strategies.hpp.
Referenced by chunk_strategies::RecursiveSubChunkStrategy< T >::apply_recursive().
The documentation for this class was generated from the following file:
sub_chunk_strategies.hpp