Chunk< T > Class Template Reference
A template class for managing and processing data in chunks.
#include <chunk.hpp>
Public Member Functions
Chunk (size_t size)
Constructs a Chunk with a specified size.
void add (const std::vector< T > &elements)
Adds a vector of elements to the chunk.
void add (const T &element)
Adds a single element to the chunk.
std::vector< std::vector< T > > chunk_by_monotonicity () const
template<typename Pred >
std::vector< std::vector< T > > chunk_by_predicate (Pred predicate) const
std::vector< std::vector< T > > chunk_by_similarity (double threshold)
std::vector< std::vector< T > > chunk_by_size (size_t size)
template<typename StatFunc >
std::vector< std::vector< T > > chunk_by_statistic (T threshold, StatFunc stat_func) const
std::vector< std::vector< T > > chunk_by_sum (T target_sum) const
std::vector< std::vector< T > > chunk_by_threshold (T threshold)
size_t chunk_count () const
std::vector< std::vector< T > > chunk_into_n (size_t n) const
std::vector< T > get_chunk (size_t index) const
Retrieves a specific chunk by index.
std::vector< std::vector< T > > get_chunks () const
Retrieves all chunks.
std::vector< std::vector< T > > get_overlapping_chunks (size_t overlap) const
std::vector< std::vector< T > > get_padded_chunks (const T &pad_value) const
size_t size () const
std::vector< std::vector< T > > sliding_window (size_t window_size, size_t step=1) const
Private Member Functions
std::vector< std::vector< T > > create_similarity_chunks (double threshold) const
std::vector< std::vector< T > > create_threshold_chunks (T threshold) const
std::vector< std::vector< T > > make_chunks (size_t size) const
void update_chunks ()
void validate_input () const
void validate_size (size_t size, const std::string &param) const
Static Private Member Functions
static double calculate_similarity (const T &a, const T &b)
Private Attributes
size_t chunk_size
std::vector< std::vector< T > > chunks
std::vector< T > data
Detailed Description
template<typename T>
class Chunk< T >
A template class for managing and processing data in chunks.
This class provides various methods for splitting data into chunks, including fixed-size chunks, overlapping chunks, and predicate-based chunking.
Template Parameters
T The type of elements stored in the chunk.
Definition at line 26 of file chunk.hpp.
Constructor & Destructor Documentation
Chunk()
template<typename T >
Chunk< T >::Chunk (size_t size) [inline], [explicit]
Constructs a Chunk with a specified size.
Parameters
size The size of each chunk.
Exceptions
std::invalid_argument if size is zero.
Definition at line 126 of file chunk.hpp.
                                : chunk_size(size) {
        if (size == 0) {
            throw std::invalid_argument("Chunk size must be greater than 0");
        }
    }
References Chunk< T >::size().
Member Function Documentation
add() [1/2]
template<typename T >
void Chunk< T >::add (const std::vector< T > & elements) [inline]
Adds a vector of elements to the chunk.
Parameters
elements The elements to add.
Definition at line 153 of file chunk.hpp.
                                           {
        data.insert(data.end(), elements.begin(), elements.end());
        update_chunks();
    }
References Chunk< T >::data, and Chunk< T >::update_chunks().
add() [2/2]
template<typename T >
void Chunk< T >::add (const T & element) [inline]
Adds a single element to the chunk.
Parameters
element The element to add.
Definition at line 144 of file chunk.hpp.
                               {
        data.push_back(element);
        update_chunks();
    }
References Chunk< T >::data, and Chunk< T >::update_chunks().
Referenced by chunk_strategies::PatternBasedStrategy< T >::apply(), chunk_strategies::AdaptiveStrategy< T >::apply(), chunk_strategies::MultiCriteriaStrategy< T >::apply(), chunk_strategies::DynamicThresholdStrategy< T >::apply(), SimilarityChunkingStrategy< T >::chunk(), and chunk_windows::SlidingWindowProcessor< T >::process().
calculate_similarity()
template<typename T >
static double Chunk< T >::calculate_similarity (const T & a, const T & b) [inline], [static], [private]
Definition at line 52 of file chunk.hpp.
                                                               {
        if constexpr (std::is_arithmetic_v<T>) {
            return std::abs(static_cast<double>(a - b));
        } else {
            throw std::runtime_error("Similarity calculation not implemented for this type");
        }
    }
Referenced by Chunk< T >::create_similarity_chunks().
chunk_by_monotonicity()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::chunk_by_monotonicity () const [inline]
Definition at line 249 of file chunk.hpp.
                                                          {
        std::vector<std::vector<T>> result;
        if (data.size() < 2)
            return {data};
        std::vector<T> current_chunk{data[0]};
        bool increasing = data[1] > data[0];
        for (size_t i = 1; i < data.size(); ++i) {
            if ((data[i] > data[i - 1]) != increasing && !current_chunk.empty()) {
                result.push_back(current_chunk);
                current_chunk.clear();
                if (i < data.size() - 1)
                    increasing = data[i + 1] > data[i];
            }
            current_chunk.push_back(data[i]);
        }
        if (!current_chunk.empty())
            result.push_back(current_chunk);
        return result;
    }
References Chunk< T >::data.
chunk_by_predicate()
template<typename T >
template<typename Pred >
std::vector< std::vector< T > > Chunk< T >::chunk_by_predicate (Pred predicate) const [inline]
Definition at line 194 of file chunk.hpp.
                                                                     {
        std::vector<std::vector<T>> result;
        if (data.empty())
            return result;
        std::vector<T> current_chunk;
        for (const T& item : data) {
            if (predicate(item) && !current_chunk.empty()) {
                result.push_back(current_chunk);
                current_chunk.clear();
            }
            current_chunk.push_back(item);
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References Chunk< T >::data.
Referenced by chunk_strategies::PatternBasedStrategy< T >::apply(), and chunk_strategies::DynamicThresholdStrategy< T >::apply().
chunk_by_similarity()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::chunk_by_similarity (double threshold) [inline]
Definition at line 287 of file chunk.hpp.
                                                                  {
        try {
            return create_similarity_chunks(threshold);
        } catch (const std::exception& e) {
            return std::vector<std::vector<T>>{data};
        }
    }
References Chunk< T >::create_similarity_chunks(), and Chunk< T >::data.
Referenced by chunk_strategies::MultiCriteriaStrategy< T >::apply(), and SimilarityChunkingStrategy< T >::chunk().
chunk_by_size()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::chunk_by_size (size_t size) [inline]
Definition at line 319 of file chunk.hpp.
                                                       {
        return make_chunks(size);
    }
References Chunk< T >::make_chunks(), and Chunk< T >::size().
chunk_by_statistic()
template<typename T >
template<typename StatFunc >
std::vector< std::vector< T > > Chunk< T >::chunk_by_statistic (T threshold, StatFunc stat_func) const [inline]
Definition at line 270 of file chunk.hpp.
                                                                                      {
        std::vector<std::vector<T>> result;
        if (data.empty())
            return result;
        std::vector<T> current_chunk{data[0]};
        for (size_t i = 1; i < data.size(); ++i) {
            if (stat_func(current_chunk) > threshold) {
                result.push_back(current_chunk);
                current_chunk.clear();
            }
            current_chunk.push_back(data[i]);
        }
        if (!current_chunk.empty())
            result.push_back(current_chunk);
        return result;
    }
References Chunk< T >::data.
Referenced by chunk_strategies::AdaptiveStrategy< T >::apply().
chunk_by_sum()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::chunk_by_sum (T target_sum) const [inline]
Definition at line 212 of file chunk.hpp.
                                                             {
        std::vector<std::vector<T>> result;
        std::vector<T> current_chunk;
        T current_sum = T();
        for (const T& item : data) {
            if (current_sum + item > target_sum && !current_chunk.empty()) {
                result.push_back(current_chunk);
                current_chunk.clear();
                current_sum = T();
            }
            current_chunk.push_back(item);
            current_sum += item;
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References Chunk< T >::data.
chunk_by_threshold()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::chunk_by_threshold (T threshold) [inline]
Definition at line 323 of file chunk.hpp.
                                                            {
        validate_input();
        if (threshold <= T{}) {
            throw std::invalid_argument("Threshold must be positive");
        }
        try {
            return create_threshold_chunks(threshold);
        } catch (const std::exception& e) {
            throw;
        }
    }
References Chunk< T >::create_threshold_chunks(), and Chunk< T >::validate_input().
chunk_count()
template<typename T >
size_t Chunk< T >::chunk_count () const [inline]
Definition at line 136 of file chunk.hpp.
                               {
        return (data.size() + chunk_size - 1) / chunk_size;
    }
References Chunk< T >::chunk_size, and Chunk< T >::data.
chunk_into_n()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::chunk_into_n (size_t n) const [inline]
Definition at line 231 of file chunk.hpp.
                                                         {
        if (n == 0)
            throw std::invalid_argument("Number of chunks must be greater than 0");
        if (data.empty())
            return std::vector<std::vector<T>>();
        n = std::min(n, data.size());
        std::vector<std::vector<T>> result(n);
        size_t base_size = data.size() / n;
        size_t remainder = data.size() % n;
        size_t pos = 0;
        for (size_t i = 0; i < n; ++i) {
            size_t chunk_size = base_size + (i < remainder ? 1 : 0);
            result[i] = std::vector<T>(data.begin() + pos, data.begin() + pos + chunk_size);
            pos += chunk_size;
        }
        return result;
    }
References Chunk< T >::chunk_size, and Chunk< T >::data.
create_similarity_chunks()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::create_similarity_chunks (double threshold) const [inline], [private]
Definition at line 61 of file chunk.hpp.
                                                                             {
        if (data.empty())
            return {};
        std::vector<std::vector<T>> result;
        std::vector<T> current_chunk;
        current_chunk.push_back(data[0]);
        for (size_t i = 1; i < data.size(); ++i) {
            double sim = calculate_similarity(data[i], data[i - 1]);
            if (sim > threshold && !current_chunk.empty()) {
                result.push_back(current_chunk);
                current_chunk.clear();
            }
            current_chunk.push_back(data[i]);
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References Chunk< T >::calculate_similarity(), and Chunk< T >::data.
Referenced by Chunk< T >::chunk_by_similarity().
create_threshold_chunks()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::create_threshold_chunks (T threshold) const [inline], [private]
Definition at line 86 of file chunk.hpp.
                                                                       {
        if (data.empty())
            return {};
        std::vector<std::vector<T>> result;
        std::vector<T> current_chunk;
        T running_sum = T{}; // Zero-initialize
        for (const T& value : data) {
            if (running_sum + value > threshold && !current_chunk.empty()) {
                result.push_back(current_chunk);
                current_chunk.clear();
                running_sum = T{};
            }
            current_chunk.push_back(value);
            running_sum += value;
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References Chunk< T >::data.
Referenced by Chunk< T >::chunk_by_threshold().
get_chunk()
template<typename T >
std::vector< T > Chunk< T >::get_chunk (size_t index) const [inline]
Retrieves a specific chunk by index.
Parameters
index The index of the chunk to retrieve.
Returns
The chunk at the specified index.
Exceptions
std::out_of_range if index is invalid.
Definition at line 172 of file chunk.hpp.
                                               {
        size_t start = index * chunk_size;
        if (start >= data.size()) {
            throw std::out_of_range("Chunk index out of range");
        }
        size_t end = std::min(start + chunk_size, data.size());
        return std::vector<T>(data.begin() + start, data.begin() + end);
    }
References Chunk< T >::chunk_size, and Chunk< T >::data.
get_chunks()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::get_chunks () const [inline]
Retrieves all chunks.
Returns
A vector of vectors, where each inner vector is a chunk.
Definition at line 162 of file chunk.hpp.
                                               {
        return chunks;
    }
References Chunk< T >::chunks.
Referenced by chunk_strategies::MultiCriteriaStrategy< T >::apply().
get_overlapping_chunks()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::get_overlapping_chunks (size_t overlap) const [inline]
Definition at line 181 of file chunk.hpp.
                                                                         {
        if (overlap >= chunk_size) {
            throw std::invalid_argument("Overlap must be less than chunk size");
        }
        std::vector<std::vector<T>> result;
        size_t step = chunk_size - overlap;
        for (size_t i = 0; i + chunk_size <= data.size(); i += step) {
            result.push_back(std::vector<T>(data.begin() + i, data.begin() + i + chunk_size));
        }
        return result;
    }
References Chunk< T >::chunk_size, and Chunk< T >::data.
get_padded_chunks()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::get_padded_chunks (const T & pad_value) const [inline]
Definition at line 295 of file chunk.hpp.
                                                                        {
        std::vector<std::vector<T>> result;
        for (size_t i = 0; i < data.size(); i += chunk_size) {
            std::vector<T> chunk;
            size_t remaining = std::min(chunk_size, data.size() - i);
            chunk.insert(chunk.end(), data.begin() + i, data.begin() + i + remaining);
            if (remaining < chunk_size) {
                chunk.insert(chunk.end(), chunk_size - remaining, pad_value);
            }
            result.push_back(chunk);
        }
        return result;
    }
References Chunk< T >::chunk_size, and Chunk< T >::data.
make_chunks()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::make_chunks (size_t size) const [inline], [private]
Definition at line 40 of file chunk.hpp.
                                                           {
        std::vector<std::vector<T>> result;
        result.reserve((data.size() + size - 1) / size);
        for (size_t i = 0; i < data.size(); i += size) {
            size_t chunk_end = std::min(i + size, data.size());
            result.emplace_back(data.begin() + i, data.begin() + chunk_end);
        }
        return result;
    }
References Chunk< T >::data, and Chunk< T >::size().
Referenced by Chunk< T >::chunk_by_size().
size()
template<typename T >
size_t Chunk< T >::size () const [inline]
Definition at line 132 of file chunk.hpp.
                        {
        return data.size();
    }
References Chunk< T >::data.
Referenced by Chunk< T >::Chunk(), Chunk< T >::chunk_by_size(), Chunk< T >::make_chunks(), and Chunk< T >::validate_size().
sliding_window()
template<typename T >
std::vector< std::vector< T > > Chunk< T >::sliding_window (size_t window_size, size_t step = 1) const [inline]
Definition at line 309 of file chunk.hpp.
                                                                                      {
        validate_size(window_size, "Window size");
        validate_size(step, "Step size");
        std::vector<std::vector<T>> result;
        for (size_t i = 0; i + window_size <= data.size(); i += step) {
            result.push_back(std::vector<T>(data.begin() + i, data.begin() + i + window_size));
        }
        return result;
    }
References Chunk< T >::data, and Chunk< T >::validate_size().
Referenced by chunk_windows::SlidingWindowProcessor< T >::process().
update_chunks()
template<typename T >
void Chunk< T >::update_chunks () [inline], [private]
Definition at line 336 of file chunk.hpp.
                         {
        chunks.clear();
        for (size_t i = 0; i < data.size(); i += chunk_size) {
            std::vector<T> chunk;
            for (size_t j = 0; j < chunk_size && i + j < data.size(); ++j) {
                chunk.push_back(data[i + j]);
            }
            chunks.push_back(chunk);
        }
    }
References Chunk< T >::chunk_size, Chunk< T >::chunks, and Chunk< T >::data.
Referenced by Chunk< T >::add(), and Chunk< T >::add().
validate_input()
template<typename T >
void Chunk< T >::validate_input () const [inline], [private]
Definition at line 111 of file chunk.hpp.
                                {
        if (data.empty()) {
            throw std::invalid_argument("Empty input: Cannot chunk empty data");
        }
        if (data.size() < chunk_size) {
            throw std::invalid_argument("Input too small: Data size must be >= chunk size");
        }
    }
References Chunk< T >::chunk_size, and Chunk< T >::data.
Referenced by Chunk< T >::chunk_by_threshold().
validate_size()
template<typename T >
void Chunk< T >::validate_size (size_t size, const std::string & param) const [inline], [private]
Definition at line 33 of file chunk.hpp.
                                                                  {
        if (size == 0) {
            throw std::invalid_argument(param + " must be greater than 0");
        }
    }
References Chunk< T >::size().
Referenced by Chunk< T >::sliding_window().
Member Data Documentation
chunk_size
template<typename T >
size_t Chunk< T >::chunk_size [private]
Definition at line 28 of file chunk.hpp.
Referenced by Chunk< T >::chunk_count(), Chunk< T >::chunk_into_n(), Chunk< T >::get_chunk(), Chunk< T >::get_overlapping_chunks(), Chunk< T >::get_padded_chunks(), Chunk< T >::update_chunks(), and Chunk< T >::validate_input().
chunks
template<typename T >
std::vector<std::vector<T> > Chunk< T >::chunks [private]
Definition at line 30 of file chunk.hpp.
Referenced by Chunk< T >::get_chunks(), and Chunk< T >::update_chunks().
data
template<typename T >
std::vector<T> Chunk< T >::data [private]
Definition at line 29 of file chunk.hpp.
Referenced by Chunk< T >::add(), Chunk< T >::add(), Chunk< T >::chunk_by_monotonicity(), Chunk< T >::chunk_by_predicate(), Chunk< T >::chunk_by_similarity(), Chunk< T >::chunk_by_statistic(), Chunk< T >::chunk_by_sum(), Chunk< T >::chunk_count(), Chunk< T >::chunk_into_n(), Chunk< T >::create_similarity_chunks(), Chunk< T >::create_threshold_chunks(), Chunk< T >::get_chunk(), Chunk< T >::get_overlapping_chunks(), Chunk< T >::get_padded_chunks(), Chunk< T >::make_chunks(), Chunk< T >::size(), Chunk< T >::sliding_window(), Chunk< T >::update_chunks(), and Chunk< T >::validate_input().
The documentation for this class was generated from the following file:
chunk.hpp