chunk_strategies::HierarchicalSubChunkStrategy< T > Class Template Reference
Strategy for hierarchical sub-chunking using multiple strategies.
#include <sub_chunk_strategies.hpp>
Public Member Functions
HierarchicalSubChunkStrategy (std::vector< std::shared_ptr< ChunkStrategy< T > > > strategies, size_t min_chunk_size=1)
Construct a hierarchical sub-chunking strategy.
std::vector< std::vector< std::vector< T > > > apply (const std::vector< std::vector< T > > &chunks) override
Apply hierarchical sub-chunking to the input chunks.
Private Member Functions
std::vector< std::vector< std::vector< T > > > apply_hierarchical (const std::vector< std::vector< T > > &chunks, size_t level)
Helper function for hierarchical chunking.
Private Attributes
size_t min_chunk_size_
std::vector< std::shared_ptr< ChunkStrategy< T > > > strategies_
Detailed Description
template<typename T>
class chunk_strategies::HierarchicalSubChunkStrategy< T >
Strategy for hierarchical sub-chunking using multiple strategies.
Template Parameters
T The type of elements to process
Definition at line 121 of file sub_chunk_strategies.hpp.
Constructor & Destructor Documentation
HierarchicalSubChunkStrategy()
template<typename T >
chunk_strategies::HierarchicalSubChunkStrategy< T >::HierarchicalSubChunkStrategy (std::vector< std::shared_ptr< ChunkStrategy< T > > > strategies, size_t min_chunk_size = 1) [inline]
Construct a hierarchical sub-chunking strategy.
Parameters
strategies Vector of strategies to apply at different levels
min_chunk_size Minimum size for chunks to be processed
Definition at line 132 of file sub_chunk_strategies.hpp.
        : strategies_(strategies), min_chunk_size_(min_chunk_size) {}
Member Function Documentation
apply()
template<typename T >
std::vector< std::vector< std::vector< T > > > chunk_strategies::HierarchicalSubChunkStrategy< T >::apply (const std::vector< std::vector< T > > & chunks) [inline], [override], [virtual]
Apply hierarchical sub-chunking to the input chunks.
Parameters
chunks The input chunks to process
Returns
A vector of vectors of vectors containing the hierarchically sub-chunked data
Implements chunk_strategies::SubChunkStrategy< T >.
Definition at line 142 of file sub_chunk_strategies.hpp.
                                                          {
        return apply_hierarchical(chunks, 0);
    }
References chunk_strategies::HierarchicalSubChunkStrategy< T >::apply_hierarchical().
Referenced by demonstrate_multi_strategy_subchunking().
apply_hierarchical()
template<typename T >
std::vector< std::vector< std::vector< T > > > chunk_strategies::HierarchicalSubChunkStrategy< T >::apply_hierarchical (const std::vector< std::vector< T > > & chunks, size_t level) [inline], [private]
Helper function for hierarchical chunking.
Parameters
chunks The chunks to process
level Current hierarchy level
Returns
Processed sub-chunks
Definition at line 154 of file sub_chunk_strategies.hpp.
                                                                            {
        std::vector<std::vector<std::vector<T>>> result;
        if (level >= strategies_.size()) {
            result.push_back(chunks);
            return result;
        }
        for (const auto& chunk : chunks) {
            if (chunk.size() <= min_chunk_size_) {
                result.push_back({chunk});
                continue;
            }
            auto sub_chunks = strategies_[level]->apply(chunk);
            auto next_level_chunks = apply_hierarchical(sub_chunks, level + 1);
            result.insert(result.end(), next_level_chunks.begin(), next_level_chunks.end());
        }
        return result;
    }
References chunk_strategies::HierarchicalSubChunkStrategy< T >::apply_hierarchical(), chunk_strategies::HierarchicalSubChunkStrategy< T >::min_chunk_size_, and chunk_strategies::HierarchicalSubChunkStrategy< T >::strategies_.
Referenced by chunk_strategies::HierarchicalSubChunkStrategy< T >::apply(), and chunk_strategies::HierarchicalSubChunkStrategy< T >::apply_hierarchical().
Member Data Documentation
min_chunk_size_
template<typename T >
size_t chunk_strategies::HierarchicalSubChunkStrategy< T >::min_chunk_size_ [private]
Definition at line 124 of file sub_chunk_strategies.hpp.
Referenced by chunk_strategies::HierarchicalSubChunkStrategy< T >::apply_hierarchical().
strategies_
template<typename T >
std::vector<std::shared_ptr<ChunkStrategy<T> > > chunk_strategies::HierarchicalSubChunkStrategy< T >::strategies_ [private]
Definition at line 123 of file sub_chunk_strategies.hpp.
Referenced by chunk_strategies::HierarchicalSubChunkStrategy< T >::apply_hierarchical().
The documentation for this class was generated from the following file:
sub_chunk_strategies.hpp