advanced_structures::SemanticBoundariesChunk< T > Class Template Reference
Semantic boundaries-based chunking implementation.
#include <advanced_structures.hpp>
Public Member Functions
SemanticBoundariesChunk (double threshold=0.5)
std::vector< std::vector< T > > chunk (const std::vector< T > &data)
Protected Member Functions
virtual bool isBoundary (const std::vector< T > &chunk)
Private Attributes
double boundary_threshold
Detailed Description
template<typename T>
class advanced_structures::SemanticBoundariesChunk< T >
Semantic boundaries-based chunking implementation.
Template Parameters
T The type of elements to be chunked
Definition at line 505 of file advanced_structures.hpp.
Constructor & Destructor Documentation
SemanticBoundariesChunk()
template<typename T >
advanced_structures::SemanticBoundariesChunk< T >::SemanticBoundariesChunk (double threshold = 0.5) [inline], [explicit]
Definition at line 510 of file advanced_structures.hpp.
: boundary_threshold(threshold) {}
Member Function Documentation
chunk()
template<typename T >
std::vector< std::vector< T > > advanced_structures::SemanticBoundariesChunk< T >::chunk (const std::vector< T > & data) [inline]
Definition at line 512 of file advanced_structures.hpp.
                                                            {
        std::vector<std::vector<T>> result;
        if (data.empty())
            return result;
        std::vector<T> current_chunk;
        for (const auto& item : data) {
            current_chunk.push_back(item);
            if (isBoundary(current_chunk)) {
                result.push_back(current_chunk);
                current_chunk.clear();
            }
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References advanced_structures::SemanticBoundariesChunk< T >::isBoundary().
Referenced by advanced_structures::SemanticBoundariesChunk< T >::isBoundary(), and TEST().
isBoundary()
template<typename T >
virtual bool advanced_structures::SemanticBoundariesChunk< T >::isBoundary (const std::vector< T > & chunk) [inline], [protected], [virtual]
Definition at line 534 of file advanced_structures.hpp.
                                                       {
        return chunk.size() >= 3; // Default implementation
    }
References advanced_structures::SemanticBoundariesChunk< T >::chunk().
Referenced by advanced_structures::SemanticBoundariesChunk< T >::chunk().
Member Data Documentation
boundary_threshold
template<typename T >
double advanced_structures::SemanticBoundariesChunk< T >::boundary_threshold [private]
Definition at line 507 of file advanced_structures.hpp.
The documentation for this class was generated from the following file:
advanced_structures.hpp