chunk_compression::ChunkCompressor< T > Class Template Reference
Compression strategies for chunk data.
#include <chunk_compression.hpp>
Static Public Member Functions
static std::vector< T > delta_decode (const std::vector< T > &chunk)
Delta decode a chunk.
static std::vector< T > delta_encode (const std::vector< T > &chunk)
Delta encode a chunk.
static std::vector< std::pair< T, size_t > > run_length_encode (const std::vector< T > &chunk)
Run-length encode a chunk.
Detailed Description
template<typename T>
class chunk_compression::ChunkCompressor< T >
Compression strategies for chunk data.
Definition at line 13 of file chunk_compression.hpp.
Member Function Documentation
delta_decode()
template<typename T >
static std::vector< T > chunk_compression::ChunkCompressor< T >::delta_decode (const std::vector< T > & chunk) [inline], [static]
Delta decode a chunk.
Parameters
chunk Delta-encoded chunk
Returns
Decoded chunk
Definition at line 67 of file chunk_compression.hpp.
                                                                {
        if (chunk.empty())
            return {};
        std::vector<T> result;
        result.reserve(chunk.size());
        result.push_back(chunk[0]);
        for (size_t i = 1; i < chunk.size(); ++i) {
            result.push_back(result.back() + chunk[i]);
        }
        return result;
    }
Referenced by TEST_F(), TEST_F(), and TEST_F().
delta_encode()
template<typename T >
static std::vector< T > chunk_compression::ChunkCompressor< T >::delta_encode (const std::vector< T > & chunk) [inline], [static]
Delta encode a chunk.
Parameters
chunk Input chunk
Returns
Delta-encoded chunk
Definition at line 47 of file chunk_compression.hpp.
                                                                {
        if (chunk.empty())
            return {};
        std::vector<T> result;
        result.reserve(chunk.size());
        result.push_back(chunk[0]);
        for (size_t i = 1; i < chunk.size(); ++i) {
            result.push_back(chunk[i] - chunk[i - 1]);
        }
        return result;
    }
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
run_length_encode()
template<typename T >
static std::vector< std::pair< T, size_t > > chunk_compression::ChunkCompressor< T >::run_length_encode (const std::vector< T > & chunk) [inline], [static]
Run-length encode a chunk.
Parameters
chunk Input chunk
Returns
Encoded chunk with value-count pairs
Definition at line 20 of file chunk_compression.hpp.
                                                                                      {
        std::vector<std::pair<T, size_t>> result;
        if (chunk.empty())
            return result;
        T current = chunk[0];
        size_t count = 1;
        for (size_t i = 1; i < chunk.size(); ++i) {
            if (chunk[i] == current) {
                ++count;
            } else {
                result.emplace_back(current, count);
                current = chunk[i];
                count = 1;
            }
        }
        result.emplace_back(current, count);
        return result;
    }
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
The documentation for this class was generated from the following file:
chunk_compression.hpp