advanced_structures::BloomFilterChunk< T > Class Template Reference
Bloom filter-based chunking implementation.
#include <advanced_structures.hpp>
Public Member Functions
BloomFilterChunk (size_t size=1024, size_t num_funcs=3)
std::vector< std::vector< T > > chunk (const std::vector< T > &data)
Protected Member Functions
virtual bool shouldSplit (const std::vector< T > &chunk)
Private Attributes
std::vector< bool > filter
size_t filter_size
size_t num_hash_functions
Detailed Description
template<typename T>
class advanced_structures::BloomFilterChunk< T >
Bloom filter-based chunking implementation.
Template Parameters
T The type of elements to be chunked
Definition at line 585 of file advanced_structures.hpp.
Constructor & Destructor Documentation
BloomFilterChunk()
template<typename T >
advanced_structures::BloomFilterChunk< T >::BloomFilterChunk (size_t size = 1024, size_t num_funcs = 3) [inline]
Definition at line 592 of file advanced_structures.hpp.
        : filter_size(size), num_hash_functions(num_funcs), filter(size, false) {}
Member Function Documentation
chunk()
template<typename T >
std::vector< std::vector< T > > advanced_structures::BloomFilterChunk< T >::chunk (const std::vector< T > & data) [inline]
Definition at line 595 of file advanced_structures.hpp.
                                                            {
        std::vector<std::vector<T>> result;
        if (data.empty())
            return result;
        std::vector<T> current_chunk;
        for (const auto& item : data) {
            current_chunk.push_back(item);
            if (shouldSplit(current_chunk)) {
                result.push_back(current_chunk);
                current_chunk.clear();
            }
        }
        if (!current_chunk.empty()) {
            result.push_back(current_chunk);
        }
        return result;
    }
References advanced_structures::BloomFilterChunk< T >::shouldSplit().
Referenced by advanced_structures::BloomFilterChunk< T >::shouldSplit(), and TEST().
shouldSplit()
template<typename T >
virtual bool advanced_structures::BloomFilterChunk< T >::shouldSplit (const std::vector< T > & chunk) [inline], [protected], [virtual]
Definition at line 617 of file advanced_structures.hpp.
                                                        {
        return chunk.size() >= 4; // Default implementation
    }
References advanced_structures::BloomFilterChunk< T >::chunk().
Referenced by advanced_structures::BloomFilterChunk< T >::chunk().
Member Data Documentation
filter
template<typename T >
std::vector<bool> advanced_structures::BloomFilterChunk< T >::filter [private]
Definition at line 589 of file advanced_structures.hpp.
filter_size
template<typename T >
size_t advanced_structures::BloomFilterChunk< T >::filter_size [private]
Definition at line 587 of file advanced_structures.hpp.
num_hash_functions
template<typename T >
size_t advanced_structures::BloomFilterChunk< T >::num_hash_functions [private]
Definition at line 588 of file advanced_structures.hpp.
The documentation for this class was generated from the following file:
advanced_structures.hpp