chunk_strategies::MultiCriteriaStrategy< T > Class Template Reference
#include <chunk_strategies.hpp>
Public Member Functions
MultiCriteriaStrategy (T similarity_threshold, size_t size_threshold)
std::vector< std::vector< T > > apply (const std::vector< T > &data) const override
Applies the chunking strategy to the data.
T get_similarity_threshold () const
size_t get_size_threshold () const
void set_similarity_threshold (T threshold)
void set_size_threshold (size_t size)
Private Attributes
T similarity_threshold_
size_t size_threshold_
Detailed Description
template<typename T>
class chunk_strategies::MultiCriteriaStrategy< T >
Definition at line 300 of file chunk_strategies.hpp.
Constructor & Destructor Documentation
MultiCriteriaStrategy()
template<typename T >
chunk_strategies::MultiCriteriaStrategy< T >::MultiCriteriaStrategy (T similarity_threshold, size_t size_threshold) [inline]
Definition at line 302 of file chunk_strategies.hpp.
        : similarity_threshold_(similarity_threshold), size_threshold_(size_threshold) {}
Member Function Documentation
apply()
template<typename T >
std::vector< std::vector< T > > chunk_strategies::MultiCriteriaStrategy< T >::apply (const std::vector< T > & data) const [inline], [override], [virtual]
Applies the chunking strategy to the data.
Parameters
data The data to chunk
Returns
A vector of chunks
Implements chunk_strategies::ChunkStrategy< T >.
Definition at line 305 of file chunk_strategies.hpp.
                                                                           {
        // Step 1: Similarity-based chunking
        chunk_processing::Chunk<T> initial_chunker(1);
        initial_chunker.add(data);
        auto similarity_chunks = initial_chunker.chunk_by_threshold(similarity_threshold_);
        // Step 2: Size-based chunking
        std::vector<std::vector<T>> result;
        for (const auto& chunk : similarity_chunks) {
            chunk_processing::Chunk<T> size_chunker(size_threshold_);
            size_chunker.add(chunk);
            auto sized_chunks = size_chunker.get_chunks();
            result.insert(result.end(), sized_chunks.begin(), sized_chunks.end());
        }
        return result;
    }
References chunk_processing::Chunk< T >::add(), chunk_processing::Chunk< T >::chunk_by_threshold(), chunk_processing::Chunk< T >::get_chunks(), chunk_strategies::MultiCriteriaStrategy< T >::similarity_threshold_, and chunk_strategies::MultiCriteriaStrategy< T >::size_threshold_.
get_similarity_threshold()
template<typename T >
T chunk_strategies::MultiCriteriaStrategy< T >::get_similarity_threshold () const [inline]
Definition at line 323 of file chunk_strategies.hpp.
                                       {
        return similarity_threshold_;
    }
References chunk_strategies::MultiCriteriaStrategy< T >::similarity_threshold_.
get_size_threshold()
template<typename T >
size_t chunk_strategies::MultiCriteriaStrategy< T >::get_size_threshold () const [inline]
Definition at line 326 of file chunk_strategies.hpp.
                                      {
        return size_threshold_;
    }
References chunk_strategies::MultiCriteriaStrategy< T >::size_threshold_.
set_similarity_threshold()
template<typename T >
void chunk_strategies::MultiCriteriaStrategy< T >::set_similarity_threshold (T threshold) [inline]
Definition at line 331 of file chunk_strategies.hpp.
                                               {
        similarity_threshold_ = threshold;
    }
References chunk_strategies::MultiCriteriaStrategy< T >::similarity_threshold_.
set_size_threshold()
template<typename T >
void chunk_strategies::MultiCriteriaStrategy< T >::set_size_threshold (size_t size) [inline]
Definition at line 334 of file chunk_strategies.hpp.
                                         {
        size_threshold_ = size;
    }
References chunk_strategies::MultiCriteriaStrategy< T >::size_threshold_.
Member Data Documentation
similarity_threshold_
template<typename T >
T chunk_strategies::MultiCriteriaStrategy< T >::similarity_threshold_ [private]
Definition at line 339 of file chunk_strategies.hpp.
Referenced by chunk_strategies::MultiCriteriaStrategy< T >::apply(), chunk_strategies::MultiCriteriaStrategy< T >::get_similarity_threshold(), and chunk_strategies::MultiCriteriaStrategy< T >::set_similarity_threshold().
size_threshold_
template<typename T >
size_t chunk_strategies::MultiCriteriaStrategy< T >::size_threshold_ [private]
Definition at line 340 of file chunk_strategies.hpp.
Referenced by chunk_strategies::MultiCriteriaStrategy< T >::apply(), chunk_strategies::MultiCriteriaStrategy< T >::get_size_threshold(), and chunk_strategies::MultiCriteriaStrategy< T >::set_size_threshold().
The documentation for this class was generated from the following file:
chunk_strategies.hpp